# build environment
FROM node as build

WORKDIR /app
ENV PATH="/app/node_modules/.bin:$PATH" 
COPY package.json /app/package.json
RUN npm install
RUN npm install react-scripts
COPY . /app
CMD [ "npm", "run", "build" ]

# production environment
FROM nginx

COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]